---
title: "Read_Raw_Data"
output: html_document
---


```{r}

library(dplyr)
library(ggplot2)
library(MASS)
library(tidyr)
library(RColorBrewer)
library(viridis)
library(readxl)
library(shiny)
library(shinydashboard)
library(leafpop)
library(leaflet)
library(stats)
library(yardstick)
library(scales)

data_path <- here::here("data/input")

if(!dir.exists(data_path)) {
  dir.create(data_dir, recursive= TRUE)
}

```

```{r}

df_surgery_2024 <- read_excel(paste0(data_path,"/20250509-Health_Data.xlsx"),sheet="SUBSET_DATA")

total_dataset <- read.csv(paste0(data_path,"/GPDataCOMPLETE_2024.csv"))

bnf_code_hist <- total_dataset %>%
  dplyr::rename(PracticeId=W00024,bnf_code=X0407020C0AAADAD,n_meds=X1,month=X202401) %>%
  dplyr::select(bnf_code,n_meds) %>%
  dplyr::group_by(bnf_code) %>%
  dplyr::summarise(freq=sum(n_meds)) %>%
  dplyr::arrange(-freq)

bnf_code_prescribed  <- nrow(bnf_code_hist)

bnf_proxy_code <- c(1:bnf_code_prescribed)

bnf_proxy_hist <- cbind(bnf_code_hist,bnf_proxy_code)

bnf_total_2024 <- sum(bnf_proxy_hist$freq)

bnf_freq_dist <- bnf_proxy_hist %>%
  dplyr::select(freq,bnf_proxy_code) %>%
  mutate(rel_freq=freq/bnf_total_2024) 

ggplot(data = bnf_freq_dist, aes(x = bnf_proxy_code, y = freq)) +
  geom_point() +
  scale_x_continuous(limits=c(0,50)) +
  labs(title = "Frequency of all available medication issued over Wales in 2024",
       y = "Number of prescriptions issued over 2024",
       x = "Index of medication code") +
  theme_minimal()

```
```{r gererate_surgery_stats}

df_summary <- df_surgery_2024 %>%
  filter(total_prescribing_patients>100) %>%
  mutate(n_monthly_2024=total_prescriptions_2024/12) %>%
  mutate(patient_prescrip_permonth = 
           total_prescriptions_2024/(total_prescribing_patients*12)) %>%
  arrange(n_monthly_2024)

```


```{r}
ggplot(data = df_summary, aes(x = n_monthly_2024, y = unique_bnf_2024, ymin=0)) +
  geom_point(colour="blue") +
  scale_fill_manual(values="blue") +
  scale_x_continuous(labels = label_comma()) +
  labs(title = "Prescription range versus rate - by surgery",
       y = "BNF Medication Range",
       x = "Average Monthly Prescription Rate in 2024") +
  theme_minimal()

```


Reflected exponential

```{r}
df_for_fit_full_range <- df_summary 

starting_val <- max(df_summary$unique_bnf_2024)

nls_log_fullrange <- nls(unique_bnf_2024 ~ a - b* exp(c * n_monthly_2024),
               data = df_for_fit_full_range,
               start = list(a = starting_val, 
                            b = starting_val, c=-0.00012))

df_summary$fullrange_fit <- predict(nls_log_fullrange, df_summary$n_monthly_2024)

new_x_fullrange <- data.frame(n_monthly_2024 = seq(min(df_summary$n_monthly_2024),
                                            2*max(df_summary$n_monthly_2024), 
                                            length.out = 373))
resid_sd <- sd(resid(nls_log_fullrange))
new_x_fullrange$predicted_y <- predict(nls_log_fullrange, new_x_fullrange)
new_x_fullrange$lwr <- new_x_fullrange$predicted_y - 1.96 * resid_sd
new_x_fullrange$upr <- new_x_fullrange$predicted_y + 1.96 * resid_sd

df_for_fit_full_range$log_fit_line <- predict(nls_log_fullrange, newdata = new_x_fullrange$n_monthly)

asymptote_fullrange <- as.integer(max(new_x_fullrange$predicted_y))

ggplot() +
  geom_point(data = df_summary, aes(x = n_monthly_2024, y = unique_bnf_2024, ymin=0,
                                    xmax=70000)) + 
  geom_ribbon(data = new_x_fullrange, aes(x = n_monthly_2024, ymin = lwr, ymax = upr),
              fill = "blue", alpha = 0.2) +
  geom_point(colour="blue") +
  scale_fill_manual(values="blue") +
  scale_x_continuous(labels = label_comma()) +
  geom_line(data = df_summary, aes(x = n_monthly_2024, y = fullrange_fit), colour = "red", alpha = 1) +
  labs(title = "Prescription data fitted with reflected exponential",
       y = "Unique BNF Codes",
       x = "Monthly Prescriptions in 2024") +
  theme_minimal()


```
```{r}
df_summary_all <- df_summary %>%
  mutate(deviation_from_fullfit = unique_bnf_2024 - fullrange_fit) 

```


Simulation of uniform distribution

```{r}
df_final_single <- data.frame(Case = integer(0), 
                       Mean = numeric(0), SD = numeric(0), Percentile_5 = numeric(0))

#create sequence for the for-loop. Each x-value is one of 372 hypothetical surgeries that has between 10 and 
#the max observed number of prescriptions a month,
#which approximates to the number of cases seen (one case per monthly prescription = max 66000)

df_seq1 <- data.frame(value = seq(from=10, to= 20000, by= 100))
df_seq2 <- data.frame(value = seq(from=22000, to= 38000, by= 200))
df_seq3 <- data.frame(value = seq(from=40000, to= 67000, by= 300))

df_seq <- rbind(df_seq1, df_seq2, df_seq3)

Case_num <- 1

#create a do loop to populate a random number of different medications for each surgery per month

for (i in df_seq$value) { #value is the number of patients in each hypothetical surgery

n_rows <- i # For each random patient case seen, one of 3883 medications will be the most appropriate
n_cols <- 100 # This repeats the selection to get the mean and sd of distinct_counts.
min_val <- 1
max_val <- asymptote_fullrange

df_prescriptions <- as.data.frame(
  replicate(n_cols, sample(min_val:max_val, n_rows, replace = TRUE))
)

colnames(df_prescriptions) <- paste0("Sample", 1:n_cols)

distinct_counts <- df_prescriptions %>%
  summarise(across(everything(),
        ~ n_distinct(.)
)) %>%
tidyr::pivot_longer(cols = everything(), names_to = "Column", values_to = "DistinctCount")  

# DistinctCount becomes for the maximum surgery size of 67000, the mean asymptotic value of 3883 different medications (in practice)
# Record the ?average distinct number of medications for each size of surgery

df_final_single[Case_num,1] <- i
df_final_single[Case_num,2] <- mean(distinct_counts$DistinctCount)
df_final_single[Case_num,3] <- sd(distinct_counts$DistinctCount)
df_final_single[Case_num,4] <- quantile(distinct_counts$DistinctCount, probs=0.05)

Case_num = Case_num +1  # Now look at the next surgery in order of size, which will have some more cases

}

```

```{r}

gplot1 <- ggplot(data=df_summary,aes(x=n_monthly_2024,y=unique_bnf_2024,ymin=0)) +
  geom_point(colour="blue") +
  scale_fill_manual(values="blue") +
  scale_x_continuous(labels = label_comma()) +
  geom_line(data=df_final_single,aes(x=Case, y=Mean),linewidth=1.0,alpha=0.6) +
  labs(title = "Simulated prescriptions - uniform random model",
       x = "Prescriptions issued per month",
       y = "Unique BNF Codes") +
  theme_minimal()


plot(gplot1)
```

Now fit to the simulated data to see if the curve function is right

```{r}
df_for_fit2 <- df_final_single

nls_log2 <- nls(Mean ~ a - b * exp(c * Case),
               data = df_for_fit2,
               start = list(a = BNFChem_range, 
                            b = BNFChem_range, c=-0.00012))
```

This graph plots the simulated data along with the reflected exponential decay fit line.  
```{r}

new_x2 <- data.frame(Case = seq(min(df_final_single$Case), max(df_final_single$Case), length.out = 100))
resid_sd2 <- sd(resid(nls_log2))
new_x2$predicted_y <- predict(nls_log2, new_x2)
new_x2$lwr <- new_x2$predicted_y - 1.96 * resid_sd2
new_x2$upr <- new_x2$predicted_y + 1.96 * resid_sd2

df_for_fit2$log_fit_line <- predict(nls_log2, newdata = new_x2$Case)
  
ggplot() +
  geom_point(data = df_for_fit2, aes(x = Case, y = Mean), alpha = 1.0) +
  geom_line(data = new_x2, aes(x = Case, y = predicted_y),
            colour = "red", alpha = 1) +
  labs(title = "Simulated uniform random model fitted with reflected exponential",
       y = "Unique BNF Codes",
       x = "Monthly Prescriptions in 2024") +
  theme_minimal()


```


```{r include=TRUE}

y_pred <- predict(nls_log2) # Predicted values from the model
y_actual <- df_for_fit2$Mean # Actual values
ss_res <- sum((y_actual - y_pred)^2) # Residual sum of squares
ss_tot <- sum((y_actual - mean(y_actual))^2) # Total sum of squares
r_squared <- 1 - (ss_res / ss_tot) # R-squared

residuals_nls <- resid(nls_log2)
hist(residuals_nls,breaks=10)
qqnorm(residuals_nls)
qqline(residuals_nls)

```

Here we go through the logic of randomly selecting from the actual medication list using the measured frequency distribution - n_monthly

```{r emulate_gp}

emulate_gp_monthly <- function(df_summary,bnf_freq_dist){

    n_surgery = nrow(df_summary)
  
    for (i in 1:n_surgery){ # We take one surgery at a time and assume each regular patient has one prescription a month.
  
    n_rows <- as.integer(df_summary$n_monthly_2024[i]) #  For each patient case seen, one of the total known number of prescribed medications are chosen, according to the measured average frequency distribution.

    n_cols <- 100
    
    bnf_code_num <- nrow(bnf_freq_dist)

    df_prescriptions <- as.data.frame(
      
        replicate(n_cols, sample(1:bnf_code_num, 
                                 n_rows, prob=bnf_freq_dist$rel_freq, replace=TRUE))
    )

    
    colnames(df_prescriptions) <- paste0("Sample", 1:n_cols)

    distinct_counts <- df_prescriptions %>%
      summarise(across(everything(),
        ~ n_distinct(.)
    )) %>%
    tidyr::pivot_longer(cols = everything(), 
                        names_to = "Column", values_to = "DistinctCount")  
    # DistinctCount becomes for the maximum surgery size of 67000, the mean asymptotic value of 3883 different medications (in practice)
  # Record the ?average distinct number of medications for each size of surgery

    df_summary$sim_range[i] <- mean(distinct_counts$DistinctCount)

    }  # next surgery
    
    return(df_summary)
} 


```
```{r run_emulate}

df_summary <- emulate_gp_monthly(df_summary,bnf_freq_dist)

```

```{r}

ggplot(data = df_summary, aes(x = n_monthly_2024, y = unique_bnf_2024)) +
    geom_point(colour="blue") +
    scale_fill_manual(values="blue") +
    scale_x_continuous(labels = label_comma()) +
    geom_line(data = df_summary, aes(x = n_monthly_2024, y = sim_range), linewidth=1, alpha = 1) +
    labs(title = "Using average medication distribution function",
       y = "BNF Medication Range",
       x = "Average Monthly Prescription Rate in 2024") +
  theme_minimal()

```
